export const SAY_HELLO="hello/SAY_HELLO"
export const SAY_SOMETHING="hello/SAY_SOMETHING"
export const SHOW_SOMETHING="hello/SHOW_SOMETHING"
export const SHOW_SOMETHING_START="hello/SHOW_SOMETHING_START"